Fix tabs

diff --git a/container-scripts/client-build b/container-scripts/client-build
--- a/container-scripts/client-build
+++ b/container-scripts/client-build
@@ -1,13 +1,13 @@
 #!/bin/sh
 
 if [ ! -f /etc/openvpn/easy-rsa/pki/issued/$1.crt ]; then
-	echo "$1.crt not found"
-	exit 1
+    echo "$1.crt not found"
+    exit 1
 fi
 
 if [ ! -f /etc/openvpn/easy-rsa/pki/private/$1.key ]; then
-        echo "$1.key not found"
-        exit 1
+    echo "$1.key not found"
+    exit 1
 fi
 
 cat /etc/openvpn/server/client_header > /etc/openvpn/client/$1.ovpn
