Fix exitCode

diff --git a/container-scripts/client-remove b/container-scripts/client-remove
--- a/container-scripts/client-remove
+++ b/container-scripts/client-remove
@@ -1,8 +1,8 @@
 #!/bin/sh
 
 if [ ! -f /etc/openvpn/easy-rsa/pki/issued/$1.crt ]; then
-        echo "$1 not found"
-        exit 1
+    echo "$1 not found"
+    exit 1
 fi
 
 cd /etc/openvpn/easy-rsa
